/* xinu.h - include all system header files */

#include <stdint.h>
#include <kernel.h>
#include <conf.h>
#include <process.h>
#include <queue.h>
#include <sched.h>
#include <semaphore.h>
#include <memory.h>
#include <bufpool.h>
#include <clock.h>
#include <mark.h>
#include <ports.h>
#include <uart.h>
#include <tty.h>
#include <device.h>
#include <interrupt.h>
#include <file.h>
#include <rfilesys.h>
#include <rdisksys.h>
#include <lfilesys.h>
//#include <ether.h>
#include <mc1322x.h>
#include <radio.h>
#include <gpio.h>
//#include <ip.h>
#include <ip6.h>
#include <net6.h>
#include <nd.h>
//#include <arp.h>
#include <netiface6.h>
#include <udp.h>
//#include <dhcp.h>
//#include <icmp.h>
//#include <nat.h>
//#include <name.h>
//#include <shell.h>
//#include <date.h>
#include <prototypes.h>
